# Generated by Django 3.1.5 on 2021-04-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique_for_date='published')),
                ('published', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('kind', models.CharField(choices=[(None, 'Выберите тип публикуемого объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('с', 'Обменяю'), ('r', 'Rent')], default='s', max_length=1)),
            ],
            options={
                'ordering': ['-published', 'title'],
                'get_latest_by': ['edited’, ’published'],
                'unique_together': {('title', 'published')},
            },
        ),
    ]
